config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about"
  resources :books, only:[:index, :create, :show, :edit, :update, :destroy]do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
   end
  resources :users, only: [:index, :show, :edit, :update]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
   user_path(current_user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
    @book_comment_new = BookComment.new
    render :index
  end


  def destroy
    @book = Book.find(params[:book_id])
    @book_comment_new = BookComment.new
    @book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    render :index
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!,except: [:top]
  before_action :correct_user,   only: [:edit, :update]

  def index
    to = Time.current.at_end_of_day
     from = (to - 6.day).at_beginning_of_day
    @books = Book.all.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
    @user = current_user
    @new_book = Book.new
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
   if @new_book.save
      flash[:notice]="You have created book successfully."
      redirect_to book_path(@new_book)
   else
      @user = current_user
      @books = Book.all
      render "index"
   end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      flash.now[:error] = @book.errors.full_messages
      render "edit"
    end
  end

  def destroy
     @book = Book.find(params[:id])
     @book.destroy
     redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
   @book = Book.find(params[:id])
   if @book.user_id != current_user.id
     redirect_to books_path
   end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!,except: [:top]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @new_book = Book.new
    @books = @user.books
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @user = current_user
    @users = User.all
    @new_book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice]="You have updated user successfully."
       redirect_to user_path(current_user)
    else
      flash.now[:error] = @user.errors.full_messages
      render "edit"
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
   @user = User.find(params[:id])
   if @user.id != current_user.id
     redirect_to user_path(current_user)
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
 <%= form_with model:[book, book_comment], remote: true do |f| %>
      <%= f.text_area :comment, placeholder: "コメントをここに" , size:'90x5'%>
      <%= f.submit "送信する" %>
      <% end %>

app/views/book_comments/_index.html.erb
 <% book.book_comments.each do |book_comment| %>
      <p><%= attachment_image_tag book_comment.user, :profile_image, fallback: "no_image.jpg", size: "50x50" %>
         <%= link_to book_comment.user.name, user_path(book_comment.user) %></td>
         <%= book_comment.comment %>
      </p>
      <% if book_comment.user == current_user %>
      <div class="comment-delete">
         <p><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn-sm btn-danger" %></p>
      </div>
      <% end %>
    <% end %>

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#new-comment").html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment_new) %>");
$("textarea").val("")

app/views/books/_book.html.erb
　  <%= form_with model: new_book, local:true do |f| %>
        <% if new_book.errors.any? %>
             <p class="err_head"><%= new_book.errors.count %> errors prohibited this book from being saved:</p>
             <ul class="err_list">
           　  <% new_book.errors.full_messages.each do |messages| %>
               <li><%= messages %></li>
              <% end %>
             </ul>
        <% end %>

          <div class="text_field">
             <%= f.label :Title %><br>
             <%= f.text_field :title%><br>
          </div>
          <div class="text_area">
        	   <%= f.label :Body %><br>
             <%= f.text_area :body%><br>
          </div>
         <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
    <% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, local:true do |f| %>
     <% if @book.errors.any? %>
        <p class="err_head"><%= @book.errors.count %> errors prohibited this book from being saved:</p>
        <ul class="err_list">
         <% @book.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
         <% end %>
        </ul>
     <% end %>
    <div class="text_field">
     <%= f.label :title %><br>
     <%= f.text_field :title %>
    </div>
    <div class="text_area">
     <%= f.label :body %><br>
     <%= f.text_area :body %>
    </div>
     <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<d>|</d>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="notice"><%= flash[:notice] %></div>

<div class="container-fluid">
  <div class="row">
     <div class="col-md-3">
          <%= render 'users/user', user: @user %>
         <h2>New book</h2>
          <%= render 'books/book', new_book: @new_book %>
     </div>
     <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
         <table class="table book-index">
           <thead>
               <tr>
                 <th></th>
                 <th>Title</th>
                 <th>Opinion</th>
                 <th colspan="2"></th>
               </tr>
           </thead>
           <tbody>
            <% @books.each do |book| %>
             <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td id ="favorite-btn<%= book.id %>" >
                <%= render "favorites/favorite-btn", book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
             </tr>
            <% end %>
           </tbody>
         </table>
     </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="notice"><%= flash[:notice] %></div>

<div class="container-fluid">
 <div class="row">
     <div class="col-md-3">
          <%= render 'users/user', user: @user %>
         <h2>New book</h2>
          <%= render 'books/book', new_book: @new_book %>
     </div>

   <div class="col-md-8 offset-md-1">
        <h1>Book detail</h1>
 　   　  <table class="table book-show">
              <tbody>
                 <tr>
                 　 <td><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "50x50" %><br>
                       <%= link_to @user.name, user_path(@user) %></td>
                    <td><%= @book.title %></td>
                  　<td><%= @book.body %></td>
                     　<% if @book.user_id == current_user.id %>
                  　<td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
                  　<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
                       <% end %>
                    <td id ="favorite-btn<%= @book.id %>" >
                       <%= render  "favorites/favorite-btn", book: @book %>
                    </td>
                    <td>コメント数：<%= @book.book_comments.count %></td>
              　  </tr>
            　</tbody>
         </table>
            <div id ="comments_area">
                <%= render  "book_comments/index", book: @book %>
            </div>
            <div id="new-comment">
                <%= render  "book_comments/form", book:@book, book_comment: @book_comment %>
            </div>
       　</div>
     </div>
 </div>

app/views/comments/_index.html.erb
 <% book.book_comments.each do |book_comment| %>
      <p><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "50x50" %>
         <%= link_to book_comment.user.name, user_path(book_comment.user) %></td>
         <%= book_comment.comment %>
      </p>
      <% if book_comment.user == current_user %>
      <div class="comment-delete">
         <p><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn-sm btn-danger" %></p>
      </div>
      <% end %>
    <% end %>

app/views/favorites/_favorite-btn.html.erb
 <% if book.favorited_by?(current_user) %>
   <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <p class="favorites">♥<%= book.favorites.count %></p>
   <% end %>
   <% else %>
   <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <p class="no-favorites"> ♡<%= book.favorites.count %> </p>
   <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<h1><strong>Welcome to <i class="fas fa-book"></i>Bookers!</strong></h1>

app/views/homes/top.html.erb
<div class="notice"><%= flash[:notice] %></div>

<div class="container">
    <div class="row">
     <div class="mx-auto" style="width: 100% ;">
       <h1>welcome to <i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
       <p>In <i class="fas fa-book"></i><strong>Bookers,</strong><br></p>
       <p>you can share and exchange your opinions , inpressions , and emotions<br></p>
       <p>about various books!</p>

      <div class="col-md-5">
      <%= link_to 'Log in', new_user_session_path, class:"btn btn-primary btn-sm btn-block"  %>
      <%= link_to 'Sign up', new_user_registration_path , class:"btn btn-success btn-sm btn-block" %>
     </div>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/91ca5c5bd0.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
  <header class="navbar navbar-fixed-top ">
    <div class="container-fluid">
    　<nav class="navbar-nav mr-auto">
        <%= link_to 'Bookers', root_path, class:"header-title" %>
      </nav>
      <nav>
       <ul class="nav navbar-nav navbar-right">
      　 <% if user_signed_in? %>
     　　　<div class="d-flex flex-row bd-highlight mb4">
     　　　　 <li>
       　     <%= link_to 'Home', user_path(current_user), class:"fas fa-home" %>
           </li>
           <li>
             <%= link_to 'Users', users_path, class:"fas fa-users" %>
           </li>
           <li>
             <%= link_to 'Books', books_path, class:"fas fa-book-open" %>
           </li>
           <li>
             <%= link_to "logout", destroy_user_session_path, class:"fas fa-sign-out-alt", method: :delete %>
           </li>
          </div>
         <% else %>
       <div class="d-flex flex-row bd-highlight mb-4">
           <li>
             <%= link_to 'Home', root_path, class:"fas fa-home" %>
           </li>
           <li>
             <%= link_to 'About', home_about_path, class:"fas fa-link" %>
           </li>
           <li>
             <%= link_to "sign up", new_user_registration_path, class:"fas fa-user-plus" %>
           </li>
           <li>
             <%= link_to "login", new_user_session_path, class:"fas fa-sign-in-alt" %>
           </li>
           </div>
         <% end %>
         </ul>
         </nav>
         </div>
         </header>
         <div class="container">
        <%= yield %>
        <footer>
          <p class="text-center">CopyRight Infratop.inc</p>
        </footer>
     </div>
  </body>
</html>

app/views/users/_user.html.erb
 <h2>User info</h2>
   <table class="table_user">
         <thead>
           　<th>
           　   <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %><br>
          　 </th>
         </thead>
          <tbody>
          　    <tr>
             　    <th>name</th>
             　    <th><%= user.name %></th>
            　  </tr>
            　  <tr>
                　 <th>introduction</th>
                　 <th><%= user.introduction %></th>
            　  </tr>
            　  <tr>
             　     <th>
                  　  <%= link_to '', edit_user_path(user), class:"fas fa-user-cog btn btn-outline-secondary btn-sm btn-block"  %>
              　　　　 </th>
             　 </tr>
          </tbody>
   </table>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model: @user, local:true do |f| %>
  <% if @user.errors.any? %>
      <p class="err_head"><%= @user.errors.count %> errors prohibited this book from being saved:</p>
      <ul class="err_list">
        <% @user.errors.full_messages.each do |messages| %>
          <li><%= messages %></li>
        <% end %>
      </ul>
  <% end %>

       <p class="Name_field">
          <%= f.label :Name_ %><br>
          <%= f.text_field :name, size: 40 %><br>
       </p>
       <p class="ProfileImage_field">
           <%= f.label :Profile_image  %><br>
           <%= f.attachment_field :profile_image %><br>
       </p>
       <p class="text_area">
           <%= f.label :Introduction %><br>
           <%= f.text_area :introduction, size: "40x5" %><br>
       </p>
           <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="notice"><%= flash[:notice] %></div>

<div class="container-fluid">
 <div class="row">
     <div class="col-md-3">
          <%= render 'users/user', user: @user %>
         <h2>New book</h2>
          <%= render 'books/book', new_book: @new_book %>
     </div>

 <div class="col-md-8 offset-md-1">
  <h1>Users</h1>
　　    <table class="table user-index">
 　　　      　　  <thead>
   　　      　　  <tr>
    　　　        　 <th>image</th>
   　　　     　  　  <th>name</th>
  　　　　      　 　  <th></th>
  　　　           </tr>
              </thead>
              <tbody>
                   <% @users.each do |user| %>
                     <tr>
                       <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "50x50" %><br>
                       <td><%= user.name %></td>
                       <td><%= link_to "Show", user_path(user) %></td>
                     </tr>
                    <% end %>
              </tbody>
        </table>
       </div>
    </div>
 </div>

app/views/users/show.html.erb
<div class="notice"><%= flash[:notice] %></div>

<div class="container-fluid">
  <div class="row">
     <div class="col-md-3">
          <%= render 'users/user', user: @user %>
         <h2>New book</h2>
          <%= render 'books/book', new_book: @new_book %>
     </div>

     <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          　　　<table class="table book-index">
                    <thead>
                       <tr>
                          <th></th>
                          <th>Title</th>
                          <th>Opinion</th>
                          <th></th>
                        </tr>
                    </thead>
                    <tbody>
                       <% @books.each do |book| %>
                       <tr>
                          <td>
                          <%= link_to user_path(@user) do %>
                          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "50x50" %>
                          <% end %>
                          </td>
                          <td><%= link_to book.title, book_path(book.id) %></td>
                          <td><%= book.body %></td>
                          <td>コメント数：<%= book.book_comments.count %></td>
                       </tr>
                       <% end %>
                    </tbody>
        　　　　  </table>

              <h3>投稿数の前日比・前週比</h3>
              <table class="table-bordered" style="width: 100%;">
                  <thead>
                      <tr>
                        <th>今日の投稿数</th>
                        <th>前日の投稿数</th>
                        <th>前日比</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <td><%= @today_book.count %></td>
                        <td><%= @yesterday_book.count %></td>
                        <% if @yesterday_book.count == 0 %>
                        <td>前日の投稿はなし</td>
                        <% else %>
                        <td><% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
                     　      <%= (@the_day_before * 100).round %>%</td>
                        <% end %>
                      </tr>
                  </tbody>
              </table>
              <table class="table-bordered" style="width: 100%;">
                  <thead>
                      <tr>
                        <th>今週の投稿数</th>
                        <th>前週の投稿数</th>
                        <th>前週比</th>
                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <td><%= @this_week_book.count %></td>
                        <td><%= @last_week_book.count %></td>
                        <% if @last_week_book.count == 0 %>
                        <td>先週の投稿はなし</td>
                        <% else %>
                      　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
                      　     <%= (@the_week_before * 100).round %>%</td>
                        <% end %>
                      </tr>
                  </tbody>
              </table>
     </div>
　</div>
</div>